# Generated by Django 4.2.2 on 2023-06-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=32),
        ),
    ]
