# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0002_auto_20191115_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='people',
            field=models.ManyToManyField(related_name='trips_attending', to='login_reg.User'),
        ),
    ]
