# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0003_auto_20191115_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.TextField(default='surviving'),
            preserve_default=False,
        ),
    ]
